name: Cache Dependencies

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f72f708

      - name: prime-cache-f72f708
        run: echo "Cache hit result - ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Install dependencies
        run: pip install fastapi
