name: Cache Dependencies

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-f72f708
        id: prime-cache-f72f708
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f72f708

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.prime-cache-f72f708.outputs.cache-hit }}"

      - name: Install dependencies
        run: pip install fastapi
